### ISSUE TITLE
cli: improve error message

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-python#524]
Trying to run a `renku run` command which produces an output which would overwrite an existing file fails with a misleading error message:
```
± |master ↑6 ↓1 ✓| → renku run python src/preprocess.py data/mydata/csv1.csv
data/mydata/preprocessed_csv1.csv
Error: There are not any detected outputs in the repository.
  (use "git rm <file>..." to remove them first)

	src/preprocess.py
	data/mydata/csv1.csv

Once you have removed files that should be used as outputs,
you can safely rerun the previous command.
```

**Comment by rokroskar** [comment]
I think the problem here is that the output file is not listed on the command line but it is already part of the git tree. Then it is overwritten but not changed (i.e. it is overwritten and identical). `renku` doesn't detect any changes in git but it sees that you specified dependencies on the command line and it's guessing that you may have meant for one of those to be an output.

**Comment by mohammad-sdsc** [comment]
I get the same error when I have a script which writes to a default output (i.e. output is not passed as a command line argument). It updates the output but the contents do not change. If the contents change, `renku run` works fine.

**Comment by Panaetius** [comment]
This is solved with the explicit inputs/outputs feature, no?

**Comment by mohammad-sdsc** [comment]
I don't think so, the problem here is the error message that lists inputs as outputs. If we don't provide explicit outputs then we might still see this message.
